version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t meesuma1 -t meesum/meesuma1:latest .
            echo $DOCKER_PASSWORD | docker login -u meesum3595 --password-stdin
            docker push meesum/meesuma1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
